# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/student/C-Test-Algorithm

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/student/C-Test-Algorithm

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/student/C-Test-Algorithm/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/student/C-Test-Algorithm/CMakeFiles /home/student/C-Test-Algorithm//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/student/C-Test-Algorithm/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named testAlgorithm

# Build rule for target.
testAlgorithm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testAlgorithm
.PHONY : testAlgorithm

# fast build rule for target.
testAlgorithm/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testAlgorithm.dir/build.make CMakeFiles/testAlgorithm.dir/build
.PHONY : testAlgorithm/fast

home/student/C-Fitness-Tracker/src/StepCountingAlgo.o: home/student/C-Fitness-Tracker/src/StepCountingAlgo.c.o
.PHONY : home/student/C-Fitness-Tracker/src/StepCountingAlgo.o

# target to build an object file
home/student/C-Fitness-Tracker/src/StepCountingAlgo.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testAlgorithm.dir/build.make CMakeFiles/testAlgorithm.dir/home/student/C-Fitness-Tracker/src/StepCountingAlgo.c.o
.PHONY : home/student/C-Fitness-Tracker/src/StepCountingAlgo.c.o

home/student/C-Fitness-Tracker/src/StepCountingAlgo.i: home/student/C-Fitness-Tracker/src/StepCountingAlgo.c.i
.PHONY : home/student/C-Fitness-Tracker/src/StepCountingAlgo.i

# target to preprocess a source file
home/student/C-Fitness-Tracker/src/StepCountingAlgo.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testAlgorithm.dir/build.make CMakeFiles/testAlgorithm.dir/home/student/C-Fitness-Tracker/src/StepCountingAlgo.c.i
.PHONY : home/student/C-Fitness-Tracker/src/StepCountingAlgo.c.i

home/student/C-Fitness-Tracker/src/StepCountingAlgo.s: home/student/C-Fitness-Tracker/src/StepCountingAlgo.c.s
.PHONY : home/student/C-Fitness-Tracker/src/StepCountingAlgo.s

# target to generate assembly for a file
home/student/C-Fitness-Tracker/src/StepCountingAlgo.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testAlgorithm.dir/build.make CMakeFiles/testAlgorithm.dir/home/student/C-Fitness-Tracker/src/StepCountingAlgo.c.s
.PHONY : home/student/C-Fitness-Tracker/src/StepCountingAlgo.c.s

home/student/C-Fitness-Tracker/src/detectionStage.o: home/student/C-Fitness-Tracker/src/detectionStage.c.o
.PHONY : home/student/C-Fitness-Tracker/src/detectionStage.o

# target to build an object file
home/student/C-Fitness-Tracker/src/detectionStage.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testAlgorithm.dir/build.make CMakeFiles/testAlgorithm.dir/home/student/C-Fitness-Tracker/src/detectionStage.c.o
.PHONY : home/student/C-Fitness-Tracker/src/detectionStage.c.o

home/student/C-Fitness-Tracker/src/detectionStage.i: home/student/C-Fitness-Tracker/src/detectionStage.c.i
.PHONY : home/student/C-Fitness-Tracker/src/detectionStage.i

# target to preprocess a source file
home/student/C-Fitness-Tracker/src/detectionStage.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testAlgorithm.dir/build.make CMakeFiles/testAlgorithm.dir/home/student/C-Fitness-Tracker/src/detectionStage.c.i
.PHONY : home/student/C-Fitness-Tracker/src/detectionStage.c.i

home/student/C-Fitness-Tracker/src/detectionStage.s: home/student/C-Fitness-Tracker/src/detectionStage.c.s
.PHONY : home/student/C-Fitness-Tracker/src/detectionStage.s

# target to generate assembly for a file
home/student/C-Fitness-Tracker/src/detectionStage.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testAlgorithm.dir/build.make CMakeFiles/testAlgorithm.dir/home/student/C-Fitness-Tracker/src/detectionStage.c.s
.PHONY : home/student/C-Fitness-Tracker/src/detectionStage.c.s

home/student/C-Fitness-Tracker/src/filterStage.o: home/student/C-Fitness-Tracker/src/filterStage.c.o
.PHONY : home/student/C-Fitness-Tracker/src/filterStage.o

# target to build an object file
home/student/C-Fitness-Tracker/src/filterStage.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testAlgorithm.dir/build.make CMakeFiles/testAlgorithm.dir/home/student/C-Fitness-Tracker/src/filterStage.c.o
.PHONY : home/student/C-Fitness-Tracker/src/filterStage.c.o

home/student/C-Fitness-Tracker/src/filterStage.i: home/student/C-Fitness-Tracker/src/filterStage.c.i
.PHONY : home/student/C-Fitness-Tracker/src/filterStage.i

# target to preprocess a source file
home/student/C-Fitness-Tracker/src/filterStage.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testAlgorithm.dir/build.make CMakeFiles/testAlgorithm.dir/home/student/C-Fitness-Tracker/src/filterStage.c.i
.PHONY : home/student/C-Fitness-Tracker/src/filterStage.c.i

home/student/C-Fitness-Tracker/src/filterStage.s: home/student/C-Fitness-Tracker/src/filterStage.c.s
.PHONY : home/student/C-Fitness-Tracker/src/filterStage.s

# target to generate assembly for a file
home/student/C-Fitness-Tracker/src/filterStage.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testAlgorithm.dir/build.make CMakeFiles/testAlgorithm.dir/home/student/C-Fitness-Tracker/src/filterStage.c.s
.PHONY : home/student/C-Fitness-Tracker/src/filterStage.c.s

home/student/C-Fitness-Tracker/src/motionDetectStage.o: home/student/C-Fitness-Tracker/src/motionDetectStage.c.o
.PHONY : home/student/C-Fitness-Tracker/src/motionDetectStage.o

# target to build an object file
home/student/C-Fitness-Tracker/src/motionDetectStage.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testAlgorithm.dir/build.make CMakeFiles/testAlgorithm.dir/home/student/C-Fitness-Tracker/src/motionDetectStage.c.o
.PHONY : home/student/C-Fitness-Tracker/src/motionDetectStage.c.o

home/student/C-Fitness-Tracker/src/motionDetectStage.i: home/student/C-Fitness-Tracker/src/motionDetectStage.c.i
.PHONY : home/student/C-Fitness-Tracker/src/motionDetectStage.i

# target to preprocess a source file
home/student/C-Fitness-Tracker/src/motionDetectStage.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testAlgorithm.dir/build.make CMakeFiles/testAlgorithm.dir/home/student/C-Fitness-Tracker/src/motionDetectStage.c.i
.PHONY : home/student/C-Fitness-Tracker/src/motionDetectStage.c.i

home/student/C-Fitness-Tracker/src/motionDetectStage.s: home/student/C-Fitness-Tracker/src/motionDetectStage.c.s
.PHONY : home/student/C-Fitness-Tracker/src/motionDetectStage.s

# target to generate assembly for a file
home/student/C-Fitness-Tracker/src/motionDetectStage.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testAlgorithm.dir/build.make CMakeFiles/testAlgorithm.dir/home/student/C-Fitness-Tracker/src/motionDetectStage.c.s
.PHONY : home/student/C-Fitness-Tracker/src/motionDetectStage.c.s

home/student/C-Fitness-Tracker/src/postProcessingStage.o: home/student/C-Fitness-Tracker/src/postProcessingStage.c.o
.PHONY : home/student/C-Fitness-Tracker/src/postProcessingStage.o

# target to build an object file
home/student/C-Fitness-Tracker/src/postProcessingStage.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testAlgorithm.dir/build.make CMakeFiles/testAlgorithm.dir/home/student/C-Fitness-Tracker/src/postProcessingStage.c.o
.PHONY : home/student/C-Fitness-Tracker/src/postProcessingStage.c.o

home/student/C-Fitness-Tracker/src/postProcessingStage.i: home/student/C-Fitness-Tracker/src/postProcessingStage.c.i
.PHONY : home/student/C-Fitness-Tracker/src/postProcessingStage.i

# target to preprocess a source file
home/student/C-Fitness-Tracker/src/postProcessingStage.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testAlgorithm.dir/build.make CMakeFiles/testAlgorithm.dir/home/student/C-Fitness-Tracker/src/postProcessingStage.c.i
.PHONY : home/student/C-Fitness-Tracker/src/postProcessingStage.c.i

home/student/C-Fitness-Tracker/src/postProcessingStage.s: home/student/C-Fitness-Tracker/src/postProcessingStage.c.s
.PHONY : home/student/C-Fitness-Tracker/src/postProcessingStage.s

# target to generate assembly for a file
home/student/C-Fitness-Tracker/src/postProcessingStage.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testAlgorithm.dir/build.make CMakeFiles/testAlgorithm.dir/home/student/C-Fitness-Tracker/src/postProcessingStage.c.s
.PHONY : home/student/C-Fitness-Tracker/src/postProcessingStage.c.s

home/student/C-Fitness-Tracker/src/preProcessingStage.o: home/student/C-Fitness-Tracker/src/preProcessingStage.c.o
.PHONY : home/student/C-Fitness-Tracker/src/preProcessingStage.o

# target to build an object file
home/student/C-Fitness-Tracker/src/preProcessingStage.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testAlgorithm.dir/build.make CMakeFiles/testAlgorithm.dir/home/student/C-Fitness-Tracker/src/preProcessingStage.c.o
.PHONY : home/student/C-Fitness-Tracker/src/preProcessingStage.c.o

home/student/C-Fitness-Tracker/src/preProcessingStage.i: home/student/C-Fitness-Tracker/src/preProcessingStage.c.i
.PHONY : home/student/C-Fitness-Tracker/src/preProcessingStage.i

# target to preprocess a source file
home/student/C-Fitness-Tracker/src/preProcessingStage.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testAlgorithm.dir/build.make CMakeFiles/testAlgorithm.dir/home/student/C-Fitness-Tracker/src/preProcessingStage.c.i
.PHONY : home/student/C-Fitness-Tracker/src/preProcessingStage.c.i

home/student/C-Fitness-Tracker/src/preProcessingStage.s: home/student/C-Fitness-Tracker/src/preProcessingStage.c.s
.PHONY : home/student/C-Fitness-Tracker/src/preProcessingStage.s

# target to generate assembly for a file
home/student/C-Fitness-Tracker/src/preProcessingStage.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testAlgorithm.dir/build.make CMakeFiles/testAlgorithm.dir/home/student/C-Fitness-Tracker/src/preProcessingStage.c.s
.PHONY : home/student/C-Fitness-Tracker/src/preProcessingStage.c.s

home/student/C-Fitness-Tracker/src/ringbuffer.o: home/student/C-Fitness-Tracker/src/ringbuffer.c.o
.PHONY : home/student/C-Fitness-Tracker/src/ringbuffer.o

# target to build an object file
home/student/C-Fitness-Tracker/src/ringbuffer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testAlgorithm.dir/build.make CMakeFiles/testAlgorithm.dir/home/student/C-Fitness-Tracker/src/ringbuffer.c.o
.PHONY : home/student/C-Fitness-Tracker/src/ringbuffer.c.o

home/student/C-Fitness-Tracker/src/ringbuffer.i: home/student/C-Fitness-Tracker/src/ringbuffer.c.i
.PHONY : home/student/C-Fitness-Tracker/src/ringbuffer.i

# target to preprocess a source file
home/student/C-Fitness-Tracker/src/ringbuffer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testAlgorithm.dir/build.make CMakeFiles/testAlgorithm.dir/home/student/C-Fitness-Tracker/src/ringbuffer.c.i
.PHONY : home/student/C-Fitness-Tracker/src/ringbuffer.c.i

home/student/C-Fitness-Tracker/src/ringbuffer.s: home/student/C-Fitness-Tracker/src/ringbuffer.c.s
.PHONY : home/student/C-Fitness-Tracker/src/ringbuffer.s

# target to generate assembly for a file
home/student/C-Fitness-Tracker/src/ringbuffer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testAlgorithm.dir/build.make CMakeFiles/testAlgorithm.dir/home/student/C-Fitness-Tracker/src/ringbuffer.c.s
.PHONY : home/student/C-Fitness-Tracker/src/ringbuffer.c.s

home/student/C-Fitness-Tracker/src/scoringStage.o: home/student/C-Fitness-Tracker/src/scoringStage.c.o
.PHONY : home/student/C-Fitness-Tracker/src/scoringStage.o

# target to build an object file
home/student/C-Fitness-Tracker/src/scoringStage.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testAlgorithm.dir/build.make CMakeFiles/testAlgorithm.dir/home/student/C-Fitness-Tracker/src/scoringStage.c.o
.PHONY : home/student/C-Fitness-Tracker/src/scoringStage.c.o

home/student/C-Fitness-Tracker/src/scoringStage.i: home/student/C-Fitness-Tracker/src/scoringStage.c.i
.PHONY : home/student/C-Fitness-Tracker/src/scoringStage.i

# target to preprocess a source file
home/student/C-Fitness-Tracker/src/scoringStage.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testAlgorithm.dir/build.make CMakeFiles/testAlgorithm.dir/home/student/C-Fitness-Tracker/src/scoringStage.c.i
.PHONY : home/student/C-Fitness-Tracker/src/scoringStage.c.i

home/student/C-Fitness-Tracker/src/scoringStage.s: home/student/C-Fitness-Tracker/src/scoringStage.c.s
.PHONY : home/student/C-Fitness-Tracker/src/scoringStage.s

# target to generate assembly for a file
home/student/C-Fitness-Tracker/src/scoringStage.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testAlgorithm.dir/build.make CMakeFiles/testAlgorithm.dir/home/student/C-Fitness-Tracker/src/scoringStage.c.s
.PHONY : home/student/C-Fitness-Tracker/src/scoringStage.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testAlgorithm.dir/build.make CMakeFiles/testAlgorithm.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testAlgorithm.dir/build.make CMakeFiles/testAlgorithm.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testAlgorithm.dir/build.make CMakeFiles/testAlgorithm.dir/src/main.c.s
.PHONY : src/main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... testAlgorithm"
	@echo "... home/student/C-Fitness-Tracker/src/StepCountingAlgo.o"
	@echo "... home/student/C-Fitness-Tracker/src/StepCountingAlgo.i"
	@echo "... home/student/C-Fitness-Tracker/src/StepCountingAlgo.s"
	@echo "... home/student/C-Fitness-Tracker/src/detectionStage.o"
	@echo "... home/student/C-Fitness-Tracker/src/detectionStage.i"
	@echo "... home/student/C-Fitness-Tracker/src/detectionStage.s"
	@echo "... home/student/C-Fitness-Tracker/src/filterStage.o"
	@echo "... home/student/C-Fitness-Tracker/src/filterStage.i"
	@echo "... home/student/C-Fitness-Tracker/src/filterStage.s"
	@echo "... home/student/C-Fitness-Tracker/src/motionDetectStage.o"
	@echo "... home/student/C-Fitness-Tracker/src/motionDetectStage.i"
	@echo "... home/student/C-Fitness-Tracker/src/motionDetectStage.s"
	@echo "... home/student/C-Fitness-Tracker/src/postProcessingStage.o"
	@echo "... home/student/C-Fitness-Tracker/src/postProcessingStage.i"
	@echo "... home/student/C-Fitness-Tracker/src/postProcessingStage.s"
	@echo "... home/student/C-Fitness-Tracker/src/preProcessingStage.o"
	@echo "... home/student/C-Fitness-Tracker/src/preProcessingStage.i"
	@echo "... home/student/C-Fitness-Tracker/src/preProcessingStage.s"
	@echo "... home/student/C-Fitness-Tracker/src/ringbuffer.o"
	@echo "... home/student/C-Fitness-Tracker/src/ringbuffer.i"
	@echo "... home/student/C-Fitness-Tracker/src/ringbuffer.s"
	@echo "... home/student/C-Fitness-Tracker/src/scoringStage.o"
	@echo "... home/student/C-Fitness-Tracker/src/scoringStage.i"
	@echo "... home/student/C-Fitness-Tracker/src/scoringStage.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

